apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deployment
  name: nginx-exposed
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9889
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
